title: Surfer 
author:
  name: Konstantinos Chorianopoulos
  email: surfer@epidro.me
description: >- # this means to ignore newlines until "baseurl:"
  Image gallery (similar to Instagram, minus the vanity) with
  photos about surfing. You can follow the updates with the
  RSS feed, email a private message, or post a public comment
  at the respective Github Issue.

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

minima:
  skin: dark
  social_links:
    github: epidrome

collections:
  photos:
    output: true
    permalink: /:slug

defaults:
  -
    scope:
      path: ""
      type: "photos"
    values:
      layout: "photos"
